- hosts: web1c
  tasks:
  
  - name: Update hostname
    import_role:
      name: ansible-role-hostname
    vars:
      server_name: "{{ inventory_hostname }}"

  - name: Install Prerequisites
    import_role:
      name: ansible-role-prerequisites
  
  - include_tasks: "{{ ansible_os_family }}-clone.yml" 

  - name: Install openjdk
    import_role:
      name: ansible-role-openjdk