# - name: Update apt-get repo and cache
#   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

# - name: Upgrade all apt packages
#   apt: upgrade=dist force_apt_get=yes

-  name: java
   apt:
     name:
      - "{{ ojdk_11_Ub }}"
      - "{{ ojdk_8_Deb }}"
     state: "{{ desired_state }}"
     force_apt_get: yes
     update_cache: yes


- name: etc environment
  shell: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 chdir=/home/ubuntu/spring-petclinic

- name: etc profile
  shell: export  PATH=$PATH:$JAVA_HOME/bin chdir=/home/ubuntu/spring-petclinic

- name: bash_profile
  shell: |
    echo JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64  > /home/ubuntu/spring-petclinic/.profile
    
- name: source
  shell: source "{{ centos_home }}"spring-petclinic/.profile
  become: yes
  args:
    creates: /bin/bash

- name: install mvnw
  shell:   ./mvnw package     chdir=/home/ubuntu/spring-petclinic

- name: Run java on background
  shell: 'nohup java -jar  "{{ ubuntu_home }}"spring-petclinic/target/*.jar  & ' 